name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
        run: |
          zip -r portfolio-2025.zip . -x "*.git*"
          aws s3 cp portfolio-2025.zip s3://$S3_BUCKET_NAME/
          aws elasticbeanstalk create-application-version --application-name portfolio-2025 --version-label $(date +%s) --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key=portfolio-2025.zip
          aws elasticbeanstalk update-environment --environment-name $EB_ENV_NAME --version-label $(date +%s)
